### ISSUE TITLE
404 not found for zip

### ISSUE THREAD

**Issue by Eatham532** [QuiltMC/quilt-meta#6]
According to meta.quiltmc.org to get a zip you use `/v3/versions/loader/:game_version/:loader_version/profile/zip`

But when using it to get the zip. E.g. https://meta.quiltmc.org/v3/versions/loader/1.19/0.17.1-beta.6/profile/zip. You get a 404 error. 
![image](https://user-images.githubusercontent.com/78714349/178685325-f0213733-9b8b-4100-b0de-b009a76fd9bf.png)

**Comment by Akarys42** [comment]
We've decided to drop that endpoint. Not sure why it made it into the documentation, but it has never been implemented.
